### ISSUE TITLE
训练阶段对training图像做灰度处理的问题

### ISSUE THREAD

**Issue by wuqikui** [liutongkun/FAIR#1]
刚才发你邮件提了个问题，在这里也发一遍以防收不到：
对toothbrush（牙刷）数据集，training数据集里的无缺陷图像，牙刷毛的颜色是多变的，那么如果训练先做灰度处理，怎么让网络学习 到底该输出怎样的牙刷毛的颜色？
在测试集里，牙刷毛的颜色并没有作为一种缺陷，那么testing流程中，把图像变成灰度再输入到网络，怎么保证输出的牙刷毛的颜色和原来的一样？检测性能下降了怎么办？

**Comment by liutongkun** [comment]
首先就toothbrush重构效果而言，目前没有发现你说的颜色重构不好的问题

图像灰度化相当于把原本的 [R,G,B]映射成了一个单值gray;；
公式通常是gray = 0.2989R+0.587G+0.114B;

这一过程信息是有损的，网络要把一个gray还原成RGB需要根据正常样本提供的先验来做，这样有助于异常检测；
公式里可以看出一般而言，对于不同的颜色，比如正常的红毛，蓝毛，黄毛牙刷，它们的RGB不同，转成的gray也不同（这个你可以把它们转为灰度图看一下），所以网络在训练过程一般不会混淆；

你关注的问题可能是，如果正常样本中恰好有RGB不同的像素但能映射到同一灰度值的像素，会不会使干扰网络训练；这种情况理论上可能有，但实际出现的概率非常低，因为网络还会根据上下文信息判断；举个例子，对于真实世界采集的图像而言，一个红色的东西，它周边根据光照可能还会有淡红的影子以及各种过渡的颜色；即使红色的灰度值恰好等于其他某个颜色的灰度值，但也很难保证它周边的影子与过渡颜色也能恰好相同；这意味着网络还是能根据上下文信息判断该灰度值对应的到底该是什么颜色

除此之外还有一种相对复杂的办法是，你可以提前统计training set的色彩分布，自适应的设计灰度化公式，避免不同颜色落在同一灰度值的问题上。这样做理论上可能更好一些，但实际上我觉得没什么必要，简单的灰度化其实大多数情况已经够了

**Comment by liutongkun** [comment]
我在github上回复你了~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liutongkun/FAIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 下午2:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liutongkun/FAIR] 训练阶段对training图像做灰度处理的问题 (Issue #1)





 
刚才发你邮件提了个问题，在这里也发一遍以防收不到：
 对toothbrush（牙刷）数据集，training数据集里的无缺陷图像，牙刷毛的颜色是多变的，那么如果训练先做灰度处理，怎么让网络学习 到底该输出怎样的牙刷毛的颜色？
 在测试集里，牙刷毛的颜色并没有作为一种缺陷，那么testing流程中，把图像变成灰度再输入到网络，怎么保证输出的牙刷毛的颜色和原来的一样？检测性能下降了怎么办？

**Comment by wuqikui** [comment]
明白了 谢谢



在 2023-11-10 15:37:16，"liutongkun" ***@***.***> 写道：

首先就toothbrush重构效果而言，目前没有发现你说的颜色重构不好的问题

图像灰度化相当于把原本的 [R,G,B]映射成了一个单值gray;；
公式通常是gray = 0.2989R+0.587G+0.114B;

这一过程信息是有损的，网络要把一个gray还原成RGB需要根据正常样本提供的先验来做，这样有助于异常检测；
公式里可以看出一般而言，对于不同的颜色，比如正常的红毛，蓝毛，黄毛牙刷，它们的RGB不同，转成的gray也不同（这个你可以把它们转为灰度图看一下），所以网络在训练过程一般不会混淆；

你关注的问题可能是，如果正常样本中恰好有RGB不同的像素但能映射到同一灰度值的像素，会不会使干扰网络训练；这种情况理论上可能有，但实际出现的概率非常低，因为网络还会根据上下文信息判断；举个例子，对于真实世界采集的图像而言，一个红色的东西，它周边根据光照可能还会有淡红的影子以及各种过渡的颜色；即使红色的灰度值恰好等于其他某个颜色的灰度值，但也很难保证它周边的影子与过渡颜色也能恰好相同；这意味着网络还是能根据上下文信息判断该灰度值对应的到底该是什么颜色

除此之外还有一种相对复杂的办法是，你可以根据training set的色彩分布公式，自适应的设计灰度化公式，避免不同颜色落在同一灰度值的问题上。这样做理论上可能更好一些，但实际上我觉得没什么必要，简单的灰度化其实大多数情况已经够了
