### ISSUE TITLE
How to solve this problem?IndexError: list index out of range

### ISSUE THREAD

**Issue by bingcaipeiqiucha** [liutongkun/FAIR#3]
Traceback (most recent call last):
  File "D:\PyProject\FAIR-main\test.py", line 204, in <module>
    test(obj_list,args.data_path, args.checkpoint_path, args.base_model_name,args.saveimages)
  File "D:\PyProject\FAIR-main\test.py", line 125, in test
    all_fprs, all_pros = compute_pro(
  File "D:\PyProject\FAIR-main\pro_curve_util.py", line 156, in compute_pro
    collect_anomaly_scores(anomaly_maps, ground_truth_maps)
  File "D:\PyProject\FAIR-main\pro_curve_util.py", line 97, in collect_anomaly_scores
    len(ground_truth_maps) * ground_truth_maps[0].size)
IndexError: list index out of range

How to solve this problem?

**Comment by liutongkun** [comment]
Hi, what dataset did you use?  It seems that your ground_truth path is incorrect?

**Comment by liutongkun** [comment]
Our code runs on Ubuntu 20.04. For Windows systems, it may be necessary to modify the relevant paths under data-loader. py. For example, " mask_path = os.path.join(dir_path, '../../ground_truth/')", its '/' may no longer be suitable, as your path typically involve "\\"

**Comment by bingcaipeiqiucha** [comment]
> 您好，您使用了什么数据集？看来你的ground_truth路径不正确？

I am using the mvtec dataset.

**Comment by bingcaipeiqiucha** [comment]
> > 您好，您使用了什么数据集？看来你的ground_truth路径不正确？
> 
> I am using the mvtec dataset.

├─bottle
│  ├─ground_truth
│  │  ├─broken_large
│  │  ├─broken_small
│  │  └─contamination
│  ├─test
│  │  ├─broken_large
│  │  ├─broken_small
│  │  ├─contamination
│  │  └─good
│  └─train
│      └─good
├─cable
│  ├─ground_truth
│  │  ├─bent_wire
│  │  ├─cable_swap
│  │  ├─combined
│  │  ├─cut_inner_insulation
│  │  ├─cut_outer_insulation
│  │  ├─missing_cable
│  │  ├─missing_wire
│  │  └─poke_insulation
│  ├─test
│  │  ├─bent_wire
│  │  ├─cable_swap
│  │  ├─combined
│  │  ├─cut_inner_insulation
│  │  ├─cut_outer_insulation
│  │  ├─good
│  │  ├─missing_cable
│  │  ├─missing_wire
│  │  └─poke_insulation
│  └─train
│      └─good

This is the structure of a small part of the data.

**Comment by bingcaipeiqiucha** [comment]
> > > 您好，您使用了什么数据集？看来你的ground_truth路径不正确？
> > 
> > 
> > I am using the mvtec dataset.
> 
> ├─bottle │ ├─ground_truth │ │ ├─broken_large │ │ ├─broken_small │ │ └─contamination │ ├─test │ │ ├─broken_large │ │ ├─broken_small │ │ ├─contamination │ │ └─good │ └─train │ └─good ├─cable │ ├─ground_truth │ │ ├─bent_wire │ │ ├─cable_swap │ │ ├─combined │ │ ├─cut_inner_insulation │ │ ├─cut_outer_insulation │ │ ├─missing_cable │ │ ├─missing_wire │ │ └─poke_insulation │ ├─test │ │ ├─bent_wire │ │ ├─cable_swap │ │ ├─combined │ │ ├─cut_inner_insulation │ │ ├─cut_outer_insulation │ │ ├─good │ │ ├─missing_cable │ │ ├─missing_wire │ │ └─poke_insulation │ └─train │ └─good
> 
> This is the structure of a small part of the data.

Thank you very much for your help. I've already solved this problem.
